import json
import re

# Read the JSON file
with open('feature/workout/src/main/assets/exercises.json', 'r', encoding='utf-8') as f:
    exercises = json.load(f)

# Dictionary for common exercise terms translations
translations = {
    "Stand": "Встаньте",
    "Lie": "Лягте",
    "Sit": "Сядьте",
    "Place": "Поместите",
    "Position": "Положите",
    "Hold": "Удерживайте",
    "Keep": "Держите",
    "Maintain": "Поддерживайте",
    "Bend": "Согните",
    "Extend": "Выпрямите",
    "Lift": "Поднимите",
    "Lower": "Опустите",
    "Raise": "Поднимите",
    "Pull": "Тяните",
    "Push": "Толкайте",
    "Press": "Жмите",
    "Squeeze": "Сжимайте",
    "Contract": "Сокращайте",
    "Relax": "Расслабьте",
    "Return": "Вернитесь",
    "Repeat": "Повторите",
    "Pause": "Пауза",
    "Breath": "Дышите",
    "Inhale": "Вдыхайте",
    "Exhale": "Выдыхайте",
    "Start": "Начните",
    "Begin": "Начинайте",
    "End": "Конец",
    "Feet": "Ступни",
    "Foot": "Ступня",
    "Hands": "Руки",
    "Hand": "Рука",
    "Arms": "Руки",
    "Arm": "Рука",
    "Legs": "Ноги",
    "Leg": "Нога",
    "Knees": "Колени",
    "Knee": "Колено",
    "Hips": "Бедра",
    "Hip": "Бедро",
    "Chest": "Грудь",
    "Back": "Спина",
    "Shoulders": "Плечи",
    "Shoulder": "Плечо",
    "Elbow": "Локоть",
    "Elbows": "Локти",
    "Wrist": "Запястье",
    "Wrists": "Запястья",
    "Head": "Голова",
    "Neck": "Шея",
    "Torso": "Торс",
    "Floor": "Пол",
    "Ground": "Пол",
    "Weight": "Вес",
    "Weights": "Веса",
    "Bar": "Гриф",
    "Barbell": "Штанга",
    "Dumbbell": "Гантель",
    "Dumbbells": "Гантели",
    "Kettlebell": "Гиря",
    "Plate": "Блин",
    "Body": "Тело",
    "Bodyweight": "Собственный вес",
    "Grip": "Хват",
    "Grasp": "Захват",
    "Grab": "Возьмите",
    "Rotate": "Поверните",
    "Movement": "Движение",
    "Position": "Положение",
    "Angle": "Угол",
    "Side": "Сторона",
    "Sides": "Стороны",
    "Forward": "Вперед",
    "Backward": "Назад",
    "Up": "Вверх",
    "Down": "Вниз",
    "Left": "Левый",
    "Right": "Правый",
    "Straight": "Прямой",
    "Bent": "Согнутый",
    "Horizontal": "Горизонтальный",
    "Vertical": "Вертикальный",
    "Parallel": "Параллельно",
    "Perpendicular": "Перпендикулярно",
    "Slowly": "Медленно",
    "Quickly": "Быстро",
    "Chest": "Грудь",
    "Muscle": "Мышца",
    "Muscles": "Мышцы",
    "Abs": "Пресс",
    "Abdominals": "Пресс",
    "Core": "Кор",
    "Biceps": "Бицепс",
    "Triceps": "Трицепс",
    "Lats": "Широчайшие",
    "Delts": "Дельты",
    "Traps": "Трапеция",
    "Quads": "Квадрицепс",
    "Hamstrings": "Бицепс бедра",
    "Glutes": "Ягодицы",
    "Calves": "Икры",
    "Forearms": "Предплечья",
    "Lower back": "Поясница",
    "Shoulders": "Плечи",
    "Palms": "Ладони",
    "Palm": "Ладонь",
    "Facing": "Обращены",
    "Towards": "К",
    "Away": "От",
    "Bench": "Скамья",
    "Rack": "Стойка",
    "Machine": "Тренажер",
    "Mat": "Коврик",
    "Ball": "Мяч",
    "Band": "Эспандер",
    "Cable": "Трос",
    "Rope": "Канат",
    "Chain": "Цепь",
    "Box": "Ящик",
    "Platform": "Платформа",
    "Step": "Шаг",
    "Steps": "Шаги",
    "Rep": "Повторение",
    "Reps": "Повторения",
    "Set": "Подход",
    "Sets": "Подходы",
    "Count": "Счет",
    "Distance": "Расстояние",
    "Time": "Время",
    "Second": "Секунда",
    "Seconds": "Секунды",
    "Minute": "Минута",
    "Minutes": "Минуты",
    "Inch": "Дюйм",
    "Inches": "Дюймы",
    "Degree": "Градус",
    "Degrees": "Градусы",
    "Level": "Уровень",
    "Height": "Высота",
    "Width": "Ширина",
    "Medium": "Средний",
    "Narrow": "Узкий",
    "Wide": "Широкий",
    "Heel": "Пятка",
    "Heels": "Пятки",
    "Toe": "Палец",
    "Toes": "Пальцы",
    "Ankle": "Лодыжка",
    "Ankles": "Лодыжки",
    "Focus": "Сосредоточьтесь",
    "Ensure": "Убедитесь",
    "Make sure": "Убедитесь",
    "Be careful": "Будьте осторожны",
    "Use": "Используйте",
    "Using": "Используя",
    "Without": "Без",
    "With": "С",
    "And": "и",
    "Or": "или",
    "But": "но",
    "As": "как",
    "Then": "затем",
    "Now": "теперь",
    "Next": "далее",
    "Finally": "наконец",
    "Also": "также",
    "Too": "тоже",
    "Very": "очень",
    "More": "более",
    "Less": "менее",
    "Most": "большинство",
    "Least": "меньше всего",
    "Best": "лучший",
    "Better": "лучше",
    "Good": "хороший",
    "Bad": "плохой",
    "Strong": "сильный",
    "Weak": "слабый",
    "Heavy": "тяжелый",
    "Light": "легкий",
    "Hard": "трудный",
    "Easy": "легкий",
    "Fast": "быстро",
    "Slow": "медленно",
    "High": "высокий",
    "Low": "низкий",
    "Top": "верх",
    "Bottom": "низ",
    "Middle": "середина",
    "Center": "центр",
    "Front": "перед",
    "Rear": "задняя часть",
    "Side": "сторона",
    "Between": "между",
    "Under": "под",
    "Over": "над",
    "Above": "над",
    "Below": "под",
    "Through": "через",
    "Across": "через",
    "Around": "вокруг",
    "About": "около",
    "Approximately": "приблизительно",
    "Exactly": "точно",
    "Just": "только",
    "Only": "только",
    "Both": "оба",
    "Each": "каждый",
    "Every": "каждый",
    "All": "все",
    "None": "ни один",
    "Some": "некоторые",
    "Any": "любой",
    "Same": "тот же",
    "Different": "разный",
    "Other": "другой",
    "Another": "другой",
    "Opposite": "противоположный",
    "Alternate": "Чередуйте",
    "Alternating": "Чередующийся",
    "Together": "вместе",
    "Apart": "врозь",
    "Separate": "отдельный",
    "Combined": "комбинированный",
    "Control": "контроль",
    "Controlled": "контролируемый",
    "Stable": "стабильный",
    "Stability": "стабильность",
    "Balance": "баланс",
    "Steady": "устойчивый",
    "Still": "неподвижный",
    "Move": "двигайте",
    "Moving": "движение",
    "Stop": "остановитесь",
    "Starting": "начало",
    "Starting position": "исходное положение",
    "Initial": "начальный",
    "Original": "исходный",
    "Complete": "полный",
    "Fully": "полностью",
    "Partially": "частично",
    "Slightly": "слегка",
    "Little": "немного",
    "Bit": "немного",
    "Amount": "количество",
    "Number": "число",
    "Range": "диапазон",
    "Full": "полный",
    "Half": "половина",
    "Quarter": "четверть",
    "Three quarters": "три четверти",
    "One third": "одна треть",
    "Two thirds": "две трети",
    "Percent": "процент",
    "Percentage": "процент",
}

# Function to translate English text in instructions
def translate_instruction(text):
    # Check if text contains English words (Latin alphabet)
    if not any(ord(c) < 128 and c.isalpha() for c in text):
        return text  # Already Russian or no letters
    
    # Replace common phrases
    result = text
    for en, ru in sorted(translations.items(), key=lambda x: len(x[0]), reverse=True):
        # Case-insensitive replacement
        pattern = re.compile(re.escape(en), re.IGNORECASE)
        result = pattern.sub(ru, result)
    
    return result

# Process all exercises
modified_count = 0
total_instructions = 0

for exercise in exercises:
    if 'instructions' in exercise:
        instructions = exercise['instructions']
        modified = False
        for i, instruction in enumerate(instructions):
            total_instructions += 1
            # Check if instruction has English text
            if any(ord(c) < 128 and c.isalpha() for c in instruction):
                translated = translate_instruction(instruction)
                if translated != instruction:
                    instructions[i] = translated
                    modified = True
        if modified:
            modified_count += 1

print(f"Total instructions: {total_instructions}")
print(f"Modified exercises: {modified_count}")

# Save the modified JSON to a new file first
with open('exercises_translated.json', 'w', encoding='utf-8') as f:
    json.dump(exercises, f, ensure_ascii=False, indent=2)

print("Translation complete! File saved as exercises_translated.json")
